// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using garbageDetetionApi.Context;

#nullable disable

namespace garbageDetetionApi.Migrations
{
    [DbContext(typeof(GarbageDbContext))]
    [Migration("20250606105723_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("garbageDetetionApi.Models.Garbage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DetectedObject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weather")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Garbages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ConfidenceScore = 0.95m,
                            DetectedObject = "Plastic Bottle",
                            Humidity = 45.0m,
                            ImageName = "plastic_bottle",
                            Temp = 22.5m,
                            TimeStamp = new DateTime(2025, 5, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Sunny",
                            WindSpeed = 5.2m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ConfidenceScore = 0.89m,
                            DetectedObject = "Can",
                            Humidity = 55.0m,
                            ImageName = "can",
                            Temp = 18.3m,
                            TimeStamp = new DateTime(2025, 5, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Cloudy",
                            WindSpeed = 3.8m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ConfidenceScore = 0.92m,
                            DetectedObject = "Paper",
                            Humidity = 80.0m,
                            ImageName = "paper",
                            Temp = 16.0m,
                            TimeStamp = new DateTime(2025, 5, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Rainy",
                            WindSpeed = 7.1m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ConfidenceScore = 0.88m,
                            DetectedObject = "Glass",
                            Humidity = 50.0m,
                            ImageName = "glass",
                            Temp = 20.0m,
                            TimeStamp = new DateTime(2025, 5, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Windy",
                            WindSpeed = 12.0m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ConfidenceScore = 0.90m,
                            DetectedObject = "Food Wrapper",
                            Humidity = 40.0m,
                            ImageName = "food_wrapper",
                            Temp = 24.0m,
                            TimeStamp = new DateTime(2025, 5, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Sunny",
                            WindSpeed = 4.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
