name: Trigger auto deployment for garbageapi-app

on:
  push:
    branches: 
      - master
    paths:
      - '**'
      - '.github/workflows/garbageapi-app.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GARBAGEAPIAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GARBAGEAPIAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GARBAGEAPIAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to Azure Container Registry
        run: |
          docker build -t aispiritacr.azurecr.io/garbageapi-app:${{ github.sha }} -f garbageDetetionApi/Dockerfile .
          echo "${{ secrets.GARBAGEAPIAPP_REGISTRY_PASSWORD }}" | docker login aispiritacr.azurecr.io -u ${{ secrets.GARBAGEAPIAPP_REGISTRY_USERNAME }} --password-stdin
          docker push aispiritacr.azurecr.io/garbageapi-app:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: garbageapi-app
          resourceGroup: Student
          imageToDeploy: aispiritacr.azurecr.io/garbageapi-app:${{ github.sha }}
          registryUrl: aispiritacr.azurecr.io
          registryUsername: ${{ secrets.GARBAGEAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GARBAGEAPIAPP_REGISTRY_PASSWORD }}

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-preview.3'

      - name: Run EF Core Migration
        env:
          CONN_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
        run: |
          dotnet tool install --global dotnet-ef
          dotnet restore garbageDetetionApi/garbageDetetionApi.csproj
          dotnet ef database update --project garbageDetetionApi/garbageDetetionApi.csproj --connection "$CONN_STRING"

